const products = [
  {
    id: 1,
    name: "Acer Aspire 5",
    category: "Laptop",
    price: 45000,
    description: "Budget laptop for students",
    tags: ["budget", "student", "office"],
  },
  {
    id: 2,
    name: "Dell Gaming X",
    category: "Laptop",
    price: 85000,
    description: "High performance gaming laptop",
    tags: ["gaming", "high-performance"],
  },
  {
    id: 3,
    name: "iPhone 14",
    category: "Mobile",
    price: 70000,
    description: "Premium Apple smartphone",
    tags: ["premium", "smartphone"],
  },
  {
    id: 4,
    name: "Realme Narzo",
    category: "Mobile",
    price: 12000,
    description: "Affordable Android smartphone",
    tags: ["budget", "android"],
  },
  {
    id: 5,
    name: "HP Pavilion",
    category: "Laptop",
    price: 60000,
    description: "Laptop for daily office work",
    tags: ["office", "daily-use"],
  },
  {
    id: 6,
    name: "Samsung Galaxy S23",
    category: "Mobile",
    price: 74999,
    description: "Flagship Android smartphone with pro camera",
    tags: ["premium", "android", "camera"],
  },
  {
    id: 7,
    name: "Lenovo IdeaPad Gaming 3",
    category: "Laptop",
    price: 72000,
    description: "Entry-level gaming laptop with RTX 3050",
    tags: ["gaming", "budget", "student"],
  },
  {
    id: 8,
    name: "boAt Rockerz 450",
    category: "Accessories",
    price: 1499,
    description: "Wireless over-ear headphones with 15-hour battery",
    tags: ["audio", "budget", "wireless"],
  },
  {
  id: 9,
  name: "MacBook Air M1",
  category: "Laptop",
  price: 92000,
  description: "Lightweight laptop with Apple M1 chip",
  tags: ["premium", "student", "office"],
},
{
  id: 10,
  name: "Asus ROG Strix G15",
  category: "Laptop",
  price: 105000,
  description: "High-end gaming laptop with RTX graphics",
  tags: ["gaming", "high-performance"],
},
{
  id: 11,
  name: "Redmi Note 12",
  category: "Mobile",
  price: 15999,
  description: "Affordable smartphone with AMOLED display",
  tags: ["budget", "android"],
},
{
  id: 12,
  name: "OnePlus 11R",
  category: "Mobile",
  price: 39999,
  description: "Fast performance smartphone with 120Hz display",
  tags: ["premium", "gaming", "android"],
},
{
  id: 13,
  name: "Sony WH-1000XM4",
  category: "Accessories",
  price: 24999,
  description: "Noise cancelling wireless headphones",
  tags: ["audio", "premium", "wireless"],
},
{
  id: 14,
  name: "Logitech MX Master 3",
  category: "Accessories",
  price: 8999,
  description: "Ergonomic wireless productivity mouse",
  tags: ["office", "wireless"],
},
{
  id: 15,
  name: "HP Victus 16",
  category: "Laptop",
  price: 78000,
  description: "Mid-range gaming laptop",
  tags: ["gaming", "budget"],
},
{
  id: 16,
  name: "Samsung Galaxy A54",
  category: "Mobile",
  price: 28999,
  description: "Mid-range smartphone with great camera",
  tags: ["android", "camera"],
},
{
  id: 17,
  name: "Apple iPad 10th Gen",
  category: "Tablet",
  price: 44999,
  description: "Powerful tablet for study and entertainment",
  tags: ["student", "premium"],
},
{
  id: 18,
  name: "Amazon Fire HD 10",
  category: "Tablet",
  price: 12999,
  description: "Affordable tablet for streaming",
  tags: ["budget", "entertainment"],
},
{
  id: 19,
  name: "Dell Inspiron 15",
  category: "Laptop",
  price: 52000,
  description: "Reliable laptop for office work",
  tags: ["office", "daily-use"],
},
{
  id: 20,
  name: "MSI Katana GF66",
  category: "Laptop",
  price: 89000,
  description: "Gaming laptop with Intel i7 processor",
  tags: ["gaming", "high-performance"],
},
{
  id: 21,
  name: "Nothing Phone 2",
  category: "Mobile",
  price: 44999,
  description: "Unique design smartphone with clean UI",
  tags: ["premium", "android"],
},
{
  id: 22,
  name: "JBL Flip 6",
  category: "Accessories",
  price: 11999,
  description: "Portable Bluetooth speaker",
  tags: ["audio", "wireless"],
},
{
  id: 23,
  name: "Apple Watch Series 9",
  category: "Wearable",
  price: 41999,
  description: "Smartwatch with health tracking",
  tags: ["premium", "fitness"],
},
{
  id: 24,
  name: "Mi Smart Band 7",
  category: "Wearable",
  price: 3499,
  description: "Affordable fitness tracker",
  tags: ["budget", "fitness"],
},
{
  id: 25,
  name: "Canon EOS 1500D",
  category: "Camera",
  price: 38999,
  description: "Entry-level DSLR camera",
  tags: ["camera", "student"],
},
{
  id: 26,
  name: "Nikon D5600",
  category: "Camera",
  price: 52999,
  description: "DSLR camera for photography enthusiasts",
  tags: ["camera", "premium"],
},
{
  id: 27,
  name: "Lenovo ThinkPad E14",
  category: "Laptop",
  price: 68000,
  description: "Business laptop with durable build",
  tags: ["office", "premium"],
},
{
  id: 28,
  name: "Asus VivoBook 14",
  category: "Laptop",
  price: 48000,
  description: "Compact laptop for daily use",
  tags: ["budget", "daily-use"],
},
{
  id: 29,
  name: "Samsung Galaxy Tab S9",
  category: "Tablet",
  price: 69999,
  description: "Premium Android tablet with AMOLED display",
  tags: ["premium", "android"],
},
{
  id: 30,
  name: "Boat Airdopes 141",
  category: "Accessories",
  price: 1499,
  description: "Affordable true wireless earbuds",
  tags: ["audio", "budget", "wireless"],
},
];

module.exports = products;
